locales:
  tau:
    name: Upper Tanana Keyboards
    description: >-
      Mobile OS keyboards for the Upper Tanana language from the Divvun group
      at UiT.
  en:
    name: Upper Tanana Keyboards
    description: >-
      Mobile OS keyboards for the Upper Tanana language from the Divvun group
      at UiT.
  nb:
    name: Upper Tanana tastatur
    description: Mobiltastatur for Upper Tanana fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
